spring:
  datasource:
    url: jdbc:mysql://localhost:3307/onlinebookingsystemdb
    username: root
    password: root
# below are optional properties
# you may neglect, it is just for logging purpose
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate.format_sql: true

